exclude_paths:
  - tmp
  - vendor

detectors:
  LongParameterList:
    exclude:
      - "Gitt::Commands::Config#get"
      - "Gitt::Commands::Config#set"
  ModuleInitialize:
    exclude:
      - "Gitt::Models"
  TooManyMethods:
    exclude:
      - "Gitt::Repository"
