inherit_gem:
  caliber: config/all.yml

Metrics/ParameterLists:
  Exclude:
    - "lib/gitt/commands/config.rb"
    - "lib/gitt/models/trailer.rb"

Style/MissingElse:
  Exclude:
    - "lib/gitt/sanitizers/statistic.rb"
