inherit_gem:
  caliber: config/all.yml

Metrics/CollectionLiteralLength:
  Exclude:
    - "spec/lib/gitt/commands/log_spec.rb"
Metrics/ParameterLists:
  Exclude:
    - "lib/gitt/commands/config.rb"
    - "lib/gitt/models/trailer.rb"

Style/MissingElse:
  Exclude:
    - "lib/gitt/sanitizers/statistic.rb"
