# frozen_string_literal: true

RSpec.shared_context "with Git tag" do
  let :git_tag do
    Gitt::Models::Tag[
      author_email: "test@example.com",
      author_name: "Test User",
      authored_at: 1735714800,
      authored_relative_at: "1 day ago",
      body: "Generated by Milestoner.",
      committed_at: 1735718461,
      committed_relative_at: "1 hour ago",
      committer_email: "test@example.com",
      committer_name: "Test User",
      sha: "180dec7d8ae8cbe3565a727c63c2111e49e0b737",
      signature: "",
      subject: "Version 0.0.0",
      trailers: [],
      version: "0.0.0"
    ]
  end
end
